# Linux package repository for Pacman
# Import and locally sign the key before enabling this repo:
#   curl -fsSL https://googolmo.github.io/repo/keys/repo.asc | sudo pacman-key --add -
#   sudo pacman-key --lsign-key 91FDA44879208693204E90EE9DF42B7054F1CB5B
# Then add the following line to /etc/pacman.conf:
#   Include = /etc/pacman.d/repo
[repo]
SigLevel = Required DatabaseOptional
Server = https://googolmo.github.io/repo/pacman/$arch
